name: Workflow Run Example
on:
  workflow_run:
    workflows: [Matrix Example]
    types: [completed]

permissions:
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: ./

      - name: Echo list of changed files on success
        run: |
          echo "Changed files on success:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: ./

      - name: Echo list of changed files on failure
        run: |
          echo "Changed files on failure:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
